name: Deploy Backend to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            set -e

            cd ${{ secrets.PROJECT_PATH }}

            pwd

            git fetch origin
            git checkout develop
            git reset --hard origin/develop

            npm install

            pm2 restart campus-backend

            pm2 save

            echo "Deployment completed successfully"